### ISSUE TITLE
Safari is not rendering link underlines.

### ISSUE THREAD

**Issue by zorn** [automerge/old-automerge-website#107]
When browsing the docs in Firefox, I see yellow underlines, but when I use Safari, I do not. 

I noticed this when reading the docs on my iPad, but macOS Safari also has the issue.

<img width="1608" alt="Image" src="https://github.com/user-attachments/assets/53877363-468b-4841-8f47-fd2ffa3650ec" />

<img width="1574" alt="Image" src="https://github.com/user-attachments/assets/acafc647-3eb3-4341-b3d9-ef19520893ad" />

I believe the issue is from around here:

https://github.com/automerge/automerge.github.io/blob/6246fb7419a9669230669b4dcb904827d2bbfb73/src/css/custom.css#L88-L91

When I tried this alternative CSS locally, it worked, but I'm not sure it aligns with your Infima usage (which I am unfamiliar with).

```css
article a,
article a:hover {
  text-decoration-line: underline;
  text-decoration-thickness: 3px;
  text-decoration-style: solid;
  text-decoration-color: var(--ifm-color-primary);
}
```
